title: José "Cosmvs" Torres
author: Bruno Santos & José Torres
email: email@example.com
description: Write an awesome description for your new site here. This could for example be used for SEO purposes.

collections:
  works:
  
docs_list_title: ACME Documentation
docs:

- title: About
  url: about.html

- title: Loose Archives
  url: loose-archives.html

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"
